version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb
    command: ["sh", "-c", "until pg_isready -h db -p 5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000"]
    env_file:
    - ./app/.env

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true

  test:
    build: ./app
    command: ["sh", "-c", "cd /app; pytest --maxfail=1000 --disable-warnings --tb=short --cov=. --cov-report=term-missing; flake8 .; pylint app"]
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - PYTHONPATH=/app

volumes:
  pgdata:
