"""add empresa and horario to itinerario

Revision ID: b59dc6505f75
Revises: e536008f3fd4
Create Date: 2025-07-09 18:49:40.597076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b59dc6505f75'
down_revision: Union[str, Sequence[str], None] = 'e536008f3fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itinerarios', sa.Column('empresa', sa.String(), nullable=True))
    op.add_column('itinerarios', sa.Column('horario', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerarios', 'empresa')
    op.drop_column('itinerarios', 'horario')
    # ### end Alembic commands ###
