"""initial full schema

Revision ID: e536008f3fd4
Revises: 
Create Date: 2025-07-08 15:06:39.709158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e536008f3fd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
    )
    op.create_table('admins',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), unique=True, index=True, nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
    )
    op.create_table('itinerarios',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('origem', sa.String(), nullable=False),
        sa.Column('destino', sa.String(), nullable=False),
        sa.Column('data', sa.Date(), nullable=False),
        sa.Column('admin_id', sa.Integer(), sa.ForeignKey('admins.id'), nullable=False),
    )
    op.create_table('passagens',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('nome_passageiro', sa.String(), nullable=False),
        sa.Column('telefone', sa.String(), nullable=False),
        sa.Column('tipo', sa.Enum('aviao', 'onibus', name='tipopassagemenum'), nullable=False),
        sa.Column('classe_aviao', sa.Enum('economica', 'executiva', 'primeira_classe', name='classepassagemaviaoenum'), nullable=True),
        sa.Column('tipo_poltrona_onibus', sa.Enum('cama_leito', 'semi_leito', 'executiva', 'convencional', name='tipopoltronaonibusenum'), nullable=True),
        sa.Column('itinerario_id', sa.Integer(), sa.ForeignKey('itinerarios.id'), nullable=False),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_itinerarios_id'), table_name='itinerarios')
    op.drop_table('itinerarios')
    op.drop_index(op.f('ix_passagens_id'), table_name='passagens')
    op.drop_table('passagens')
    # ### end Alembic commands ###
